msbuild BestWaySoftware.Xpf.Uwp.Native.sln /t:Clean /p:Platform=ARM /p:Configuration=Debug
msbuild BestWaySoftware.Xpf.Uwp.Native.sln /t:Clean /p:Platform=ARM /p:Configuration=Release
msbuild BestWaySoftware.Xpf.Uwp.Native.sln /t:Clean /p:Platform=x86 /p:Configuration=Debug
msbuild BestWaySoftware.Xpf.Uwp.Native.sln /t:Clean /p:Platform=x86 /p:Configuration=Release
msbuild BestWaySoftware.Xpf.Uwp.Native.sln /t:Clean /p:Platform=x64 /p:Configuration=Debug
msbuild BestWaySoftware.Xpf.Uwp.Native.sln /t:Clean /p:Platform=x64 /p:Configuration=Release
msbuild BestWaySoftware.Xpf.Uwp.Native.sln /t:Build /p:Platform=ARM /p:Configuration=Debug
msbuild BestWaySoftware.Xpf.Uwp.Native.sln /t:Build /p:Platform=ARM /p:Configuration=Release
msbuild BestWaySoftware.Xpf.Uwp.Native.sln /t:Build /p:Platform=x86 /p:Configuration=Debug
msbuild BestWaySoftware.Xpf.Uwp.Native.sln /t:Build /p:Platform=x86 /p:Configuration=Release
msbuild BestWaySoftware.Xpf.Uwp.Native.sln /t:Build /p:Platform=x64 /p:Configuration=Debug
msbuild BestWaySoftware.Xpf.Uwp.Native.sln /t:Build /p:Platform=x64 /p:Configuration=Release